---
abstract: 'Interface to the CommonMark C library'
author:
  - 'Nick Wellnhofer <wellnhofer@aevum.de>'
build_requires:
  Encode: '0'
  Test::More: '0'
configure_requires:
  Devel::CheckLib: '1.05'
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.024, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CommonMark
requires:
  perl: '5.008'
resources:
  bugtracker: https://github.com/nwellnhof/perl-commonmark/issues
  repository: https://github.com/nwellnhof/perl-commonmark.git
version: '0.310100'
x_generated_by_perl: v5.34.0
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
